apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i5abr5nry-go
  janus-idp.io/tekton: i5abr5nry-go
  backstage.io/kubernetes-id: i5abr5nry-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: i5abr5nry-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
